version: "3.9"
services:
  filestorage:
    container_name: vaawel-storage-api
    image: vaawel/storage-api:latest
    restart: unless-stopped
    build:
      context: ./
      dockerfile: config/services/app/app.dockerfile
    ports:
      - "5002:8080"
    networks:
      - nginx-proxymanager_default

networks:
  nginx-proxymanager_default:
    external: true
